---
title: "lab5"
author: "Anastasia Galperina"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(tidyverse)
```

```{r}
  Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
    rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
    filter (Country_Region == "US") %>% 
    group_by(Province_State, Country_Region) %>% 
    summarise(Confirmed = sum(Confirmed)) 
```

```{r}
  str(Confirmed_State_3_13)
```

```{r}
  Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
    filter (Country_Region == "US") %>% 
    group_by(Province_State, Country_Region) %>% 
    summarise(Confirmed = sum(Confirmed)) 
```

```{r}
  str(Confirmed_State_9_13)
```

```{r}
  setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_3_13$Province_State)
```

```{r}
  Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
    filter(Province_State != "Recovered") 
```

```{r}
  Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
    Confirmed_State_9_13, by = c("Province_State"))
    head(Confirmed_State_3_13_9_13_joined)
```

```{r}
  tail(Confirmed_State_3_13_9_13_joined, 5)
```

```{r}
  which(is.na(Confirmed_State_3_13_9_13_joined))
```

```{r}
  Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
    Confirmed_State_9_13, by = c("Province_State")) %>% 
    rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
    select(-Country_Region.x, -Country_Region.y) %>% 
    replace_na(list(Confirmed_3_13_2020 = 0))
    head(Confirmed_State_3_13_9_13_joined)
```

```{r}
  which(is.na(Confirmed_State_3_13_9_13_joined))
```

# Switching between wide and long table formats

```{r}
  Confirmed_State_3_13_9_13_joined_long <- Confirmed_State_3_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
```

```{r, fig.width = 5, fig.height = 10}
  ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x = Confirmed,  y = Province_State))  + 
    geom_point(aes(color = Date)) 
```

# Working with the time series data

```{r}
   download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", 
               destfile = "data/time_series_covid19_confirmed_global.csv")

  time_series_confirmed <- read_csv("data/time_series_covid19_confirmed_global.csv")%>%
    rename(Province_State = "Province/State", Country_Region = "Country/Region")
```

```{r}
   download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")

  time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
    rename(Province_State = "Province/State", Country_Region = "Country/Region")
```

```{r}
  head(time_series_confirmed)
```

```{r}
  time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 

  head(time_series_confirmed_long)
```


```{r}
  time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 

  head(time_series_deaths_long)
```

```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
  head(time_series_confirmed_long)
```

```{r}
  time_series_deaths_long <- time_series_deaths_long %>% 
    unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
    select(Key, Deaths)
```

```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
```

```{r}
which(is.na(time_series_long_joined$Confirmed))
```

```{r}
which(is.na(time_series_long_joined$Deaths))
```

```{r}
library(lubridate)
```

```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```

```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
   pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
              names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

# Making Graphs from the time series data
```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South",
                                "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```

```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("China","France","Italy", 
                                "Korea, South", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")

```

```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```

# Excercises

#1 

  View Lab4B
  
#2 

```{r}
Confirmed_State_6_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>%
    filter (Country_Region == "US") %>% 
    group_by(Province_State, Country_Region) %>% 
    summarise(Confirmed = sum(Confirmed)) 
```

```{r}
str(Confirmed_State_6_13)
```

```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
    filter (Country_Region == "US") %>% 
    group_by(Province_State, Country_Region) %>% 
    summarise(Confirmed = sum(Confirmed)) 
```

```{r}
str(Confirmed_State_9_13)
```

```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_6_13$Province_State)
```

```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered") 
```

```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
    Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
```

```{r}
  tail(Confirmed_State_6_13_9_13_joined, 5)
```

```{r}
  which(is.na(Confirmed_State_6_13_9_13_joined))
```

```{r}
  Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
    Confirmed_State_9_13, by = c("Province_State")) %>% 
    rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
    select(-Country_Region.x, -Country_Region.y) %>% 
    replace_na(list(Confirmed_6_13_2020 = 0))
    head(Confirmed_State_6_13_9_13_joined)
```

```{r}
  which(is.na(Confirmed_State_6_13_9_13_joined))
```

```{r}
  Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
```

#3 

```{r, fig.width = 5, fig.height = 10}
  ggplot(Confirmed_State_3_13_9_13_joined_long, aes( x = Confirmed,  y = Province_State))  + 
    geom_bar(stat="identity") +
    ggtitle("US Covid Data - 6/13/20 vs 9/13/20") +
    labs(x = "Number Cases") + 
    labs(y= "Province/State")
```

#4

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Deaths"), sum) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_line() +
    ggtitle("COVID-19 Deaths Worldwide")
```

#5 

```{r}
mutated_time_series <- time_series_long_joined %>%
  mutate(combined = Deaths + Confirmed)
```

#6 

```{r}
mutated_time_series_US <- mutated_time_series %>%
  filter(Country_Region == "US") 
```
  
```{r}
  ggplot(mutated_time_series_US,aes(x = combined,  y = Date))  + 
    geom_line() +
    ggtitle("Deaths and Confirmed in US") +
    labs(x = "Number Cases") + 
    labs(y= "Province/State")
```

#7 

```{r}
top_ten_deaths <- time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarise_at(c("Deaths"), sum) %>% 
  arrange(desc(Deaths)) %>% 
  slice(1:10) 
    
  
ggplot(top_ten_deaths,aes(x = Country_Region,  y = Deaths)) + 
    geom_bar(stat="identity") +
    ggtitle("Top 10 Highest Death Tolls By Country")
```

#8

```{r, fig.width = 5, fig.height = 10}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil", "United Kingdom",
                                "Italy","Mexico", "India", "France","Spain","Iran","Peru")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
      geom_point() +
      geom_line() +
      ggtitle("Highest Death Tolls By Country")+
      facet_wrap(~Country_Region,ncol=2,scales="fixed")
```
      
#9

```{r}
US_Confirmed_TimeSeries <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")) %>%
  select(-c(UID,iso2,iso3,code3,FIPS,Admin2,Lat,Long_,Combined_Key,Country_Region))%>%
  pivot_longer(-c(Province_State),
             names_to = "Date", values_to = "Confirmed")%>%
  group_by(Province_State, Date) %>%
  summarise(Confirmed = sum(Confirmed)) %>%
  filter(Province_State %in% c("Alabama","Mississippi"))%>%
    ggplot(aes(x = Date,  y = Confirmed)) + 
      geom_point() +
      geom_line() +
      facet_wrap(~Province_Region,ncol=2) +
      ggtitle("Confirmed Cases by Province/State in US")
   
head(US_Confirmed_TimeSeries)
```


#10
```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil", "United Kingdom",
                                "Italy","Mexico", "India", "France","Spain","Iran","Peru")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
      geom_point() +
      geom_line() +
      theme_dark() +
      ggtitle("Highest Death Tolls By Country")+
      facet_wrap(~Country_Region,ncol=2,scales="fixed")
```

